# Generated by Django 4.2.5 on 2023-10-10 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_appuser_first_name_appuser_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='last_name',
        ),
    ]
